name: test
on:
  push
jobs:
  calling-workflow:
    uses: ./.github/workflows/called.yml
    with:
      username: userr
      username2: user1
    secrets:  
      password: ${{ secrets.password }}
      key: ${{secrets.token }}
