name: called workflow
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
jobs:
  job1:
    name: job_1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo ${{ inputs.username }}
