name: called workflow
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      username2:
        required: false
        type: string
    secrets:
      password:
        required: true
      key:
        required: true
jobs:
  job1:
    name: job_1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          #echo ${{ inputs.username }}
          echo "Kt"
          echo ${{ secrets.password }}
          echo ${{ secrets.elktoken }}
